2 mastodon configuring article
fedihost-co/articles pull request #21
Opened 2024-06-17 15:52 UTC by vorboyvo

Configuring instance article.

2024-06-19 16:50 UTC, psaunders requested changes

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/1.index.md
> +### Configuration
Guess we should agree on a term like "Fedihost Configuration" whenever we are talking about fedihost, to differentiate from the configuration options that are available on an instance of mastodon/peertube for admin users

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/1.index.md
> +<aside><strong>Mastodon 0</strong>
I don't think this exists, maybe just comment this out for now because we do intend to provide it at some point

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/1.index.md
> +which is often required a Mastodon instance over time if it is adding
"required on a"

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/1.index.md
> +<a href="https://masto.consultatron.com/">masto.consultatron.com</a>
Change any domains that have "masto" to "social"

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/1.index.md
> +record saying `masto.consultatron.com` it actually is saying
Masto -> social

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/1.index.md
> +on a subdomain such as `masto.consultation.com` as `consultatron.com`
masto->social

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/2.configuring.md
> +Now that you've gotten your new instance set up, it's important to
link to previous article gotten your "new instance setup"

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/2.configuring.md
> +This can be your account, but many instance hosts keep their person account
I think this could be an aside.
"Admin Account
We recommend keeping admin accounts separate. It's more secure and seprates concerns. For example consultatron's IT department controls the admin account, which limits the damage the CEO bot can do if he accidentally clicks the wrong thing"

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/2.configuring.md
> +look around the options - this article gives you more details on some of
I wouldn't say what you are going to say, especially down in the article.
So cut from "Take a look ... understand them better"

2024-06-19 16:50 UTC, psaunders commented on content/articles/3.Mastodon/2.creating/2.configuring.md
> +## Branding
OK so I think you need to structure this article a bit differently. If I follow the instructions above and open "Preferences" and then "Administration" I will be seeing the dashboard.
 <img width="1117" alt="image" src="https://github.com/fedihost-co/articles/assets/424956/d3bd60a6-77ea-4eab-9d1e-571ae5feb31c">
I think rework this article so it is basically "The X things you will want to configure on your new mastodon server"

Each heading follows the exact same pattern
"
- Heading: Change Your Branding
- Codeblock Nav: How to get to it in the menu
- Subheadings for each fields to change in that section, any quirks
"

2024-06-24 21:22 UTC, vorboyvo commented
Made suggested changes, if you'd re-review

2024-06-27 20:06 UTC, merged